# @package agent
_target_: agent.dreamer.DreamerAgent
name: dreamer
cfg: ???
obs_space: ???
act_spec: ???
grad_heads: [decoder, reward]
reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}
actor_ent: 3e-4