# @package agent
_target_: agent.plan2explore.Plan2Explore
name: plan2explore
cfg: ???
obs_space: ???
act_spec: ???
grad_heads: [decoder]
reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
actor_ent: 0 